getup:
  - getup/140_01_stageii_collect.npz
  - getup/140_01_stageii_collect_mirror.npz
  - getup/140_08_stageii_collect.npz
  - getup/140_08_stageii_collect_mirror.npz
  - getup/getup_left_collect.npz
  - getup/getup_left_collect_mirror.npz

stand:
  - stand/A1_-_Stand_stageii.npz
  - stand/A2_-_Sway_stageii.npz
  - stand/General_A2_-_Sway_t2_stageii.npz
